package com.yy.sms.mapper;

import com.yy.sms.model.Consumer;
import com.yy.sms.model.ConsumerExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int countByExample(ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int deleteByExample(ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int insert(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int insertSelective(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    List<Consumer> selectByExample(ConsumerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    Consumer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Consumer record, @Param("example") ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int updateByExample(@Param("record") Consumer record, @Param("example") ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int updateByPrimaryKeySelective(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consumer
     *
     * @mbggenerated Fri Jan 06 10:41:59 CST 2017
     */
    int updateByPrimaryKey(Consumer record);
}